Component delete command
projectsyn/commodore pull request #188
Opened 2020-09-17 13:31 UTC by chrisglass

This branch adds a `component delete <slug>` command to commodore.

It does the opposite of `component add <slug>`:

```
$ commodore component new my-awesome-component
Adding component my-awesome-component...
 > Installing component
Component my-awesome-component successfully added 🎉
$ commodore component delete my-awesome-component
Are you sure you want to delete component my-awesome-component? This action cannot be undone [y/N]: y
Component my-awesome-component successfully deleted 🎉
```

It also introduces a `--force` parameter in case the interactive confirmation is not desired (for scripts, for instance):

```
$ commodore component delete --force my-awesome-component
Component my-awesome-component successfully deleted 🎉
```

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Update tests.
- [x] Update the ./CHANGELOG.md.
- [x] Link this PR to related issues.

2020-09-17 14:29 UTC, srueg requested changes
Nice, thanks!
Only found small typos.

2020-09-17 14:29 UTC, srueg commented on tests/test_component.py
> +def test_deleting_inexistant_component(tmp_path: P):
```suggestion
def test_deleting_inexistent_component(tmp_path: P):
```

2020-09-17 14:29 UTC, srueg commented on commodore/dependency_mgmt.py
> +    This is the reverse from the createa_component_symlinks method and is used
```suggestion
    This is the reverse from the create_component_symlinks method and is used
```

2020-09-17 14:31 UTC, chrisglass commented on commodore/dependency_mgmt.py
> +    This is the reverse from the createa_component_symlinks method and is used
Thanks!

2020-09-17 14:31 UTC, chrisglass commented on tests/test_component.py
> +def test_deleting_inexistant_component(tmp_path: P):
Ah, good catch :)

2020-09-17 15:48 UTC, srueg approved these changes

2020-09-18 08:15 UTC, simu approved these changes

2020-09-18 13:53 UTC, merged