Introduce Inventory class
projectsyn/commodore pull request #240
Opened 2020-10-28 14:19 UTC by corvus-ch

This is another break out of #230. With this refactoring, everything related to inventory paths got pulled together into an `Inventory` class.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update tests.
- [x] Link this PR to related issues.

2020-10-28 14:40 UTC, simu approved these changes
Looks good. I'm currently wondering if there's enough complexity in the inventory class to warrant some tests.

2020-10-28 14:41 UTC, corvus-ch commented
> I'm currently wondering if there's enough complexity in the inventory class to warrant some tests.

Yes it does.

2020-10-28 15:40 UTC, simu requested changes

2020-10-28 15:40 UTC, simu commented on commodore/dependency_mgmt.py
>      component_names = _discover_components(cfg, "inventory")
```suggestion
    component_names = _discover_components(cfg, cfg.inventory.inventory_dir)
```

2020-10-29 09:35 UTC, simu approved these changes

2020-10-29 09:45 UTC, merged