Add OIDC integration for Lieutenant communication
projectsyn/commodore pull request #426
Opened 2022-03-22 09:12 UTC by glrf

## Checklist

- [ ] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.
- [ ] Update tests.
- [ ] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues.

2022-03-24 11:05 UTC, simu requested changes
LGTM overall. See inline comments for potential improvements.

There's more documentation (e.g. `explanation/running-commodore.adoc`) which will need to be updated at some point, but that's not urgent yet.

2022-03-24 12:08 UTC, glrf commented on commodore/tokencache.py
> +cache_name = f"{Path.home()}/.cache/commodore/token"
Thanks! Yes that's a lot better, but I didn't know where to find it

2022-03-24 12:10 UTC, glrf commented on commodore/login.py
> +    # That's racy, but it should work most of the time and if not the browser should retry
Good idea. I tried to find the status of the server through the server object and failed. I'll try to implement the health endpoint.

2022-03-25 09:00 UTC, simu approved these changes
LGTM.

I had an idea while showering this morning: We could save the Keycloak client id and discovery URL in the token file until we can fetch them from Lieutenant. That way, you only have to specify them once for any given Lieutenant instance, and Commodore can extract them from the token file, if they're not given for subsequent calls based on the provided API URL.

2022-03-25 09:23 UTC, glrf commented
> I had an idea while showering this morning: We could save the Keycloak client id and discovery URL in the token file until we can fetch them from Lieutenant. That way, you only have to specify them once for any given Lieutenant instance, and Commodore can extract them from the token file, if they're not given for subsequent calls based on the provided API URL.

I suppose that make using it a bit more convenient, but IMO not by a lot, at least for the way I use commodore right now (sourcing an env file with URL and TOKEN)

Might be a good intermediate solution. Let's see what we manage to do this sprint. I'll merge this for now.

2022-03-25 09:25 UTC, merged